#datasource
datasource.name: gz_recommend

#redis
redis.pool.max-active: 9000

#协同过滤url
recommend.collaborativeFilter.item2itemUrl: "http://192.168.2.42:29010/v1/iptv/recommend/item2item"
recommend.collaborativeFilter.user2itemUrl: "http://192.168.2.42:29010/v1/iptv/recommend/user2item"