spring:
  datasource:
    url: jdbc:mysql://${datasource.ip_port}/${datasource.name}?useUnicode=true&characterEncoding=UTF-8
    username: ${datasource.username}
    password: ${datasource.password}
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: ${datasource.maxActive}
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    host: ${redis.host}
    port: ${redis.port}
    password: ${redis.password}
    database: 1
    pool:
      max-idle: 10
      max-active: ${redis.pool.max-active}
      max-wait: 10000

#配置actuator路径
management:
  context-path: /actuator
#拦截actuator路径，保护敏感信息
security:
  basic:
    path: ${management.context-path}
  user:
    name: ${security.username}
    password: ${security.password}

#开启健康检查
eureka:
  client:
    healthcheck:
      enabled: true

#开启熔断机制
feign:
  hystrix:
    enabled: true
#熔断超时时间，默认1000ms, 建议(重试次数+1)*超时时间
hystrix:
  threadpool:
    default:
      coreSize: 50
      maximumSize: 200
      allowMaximumSizeToDivergeFromCoreSize: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 14000
#连接、请求超时时间
ribbon:
  ConnectTimeout: 2000
  ReadTimeout: 7000
  #MaxAutoRetries: 对当前实例的重试次数，默认0
  #MaxAutoRetriesNextServer: 对切换实例的重试次数，默认1

### xxl-job executor address
xxl.job.executor.appname: ${spring.application.name}
xxl.job.executor.ip:
xxl.job.executor.port: ${current.executor.port}

### xxl-job, access token
xxl.job.accessToken:

### xxl-job log path
xxl.job.executor.logpath: /log/${spring.application.name}/jobhandler
### xxl-job log retention days
xxl.job.executor.logretentiondays: 30

#ERP
iptv.portal:
  host: 111.11.189.150:8081
  portalcode: PCODE-t2gwbgzp
  sptoken: 4F673775CD9E51276730A9E8EA7EA9D2

#海报服务器前缀
post.url.prefix: https://dphd.seeingtv.com/poster